### ISSUE TITLE
Support `init` or `setup` returning something other than new instance ~13

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-construct#2]
For https://github.com/canjs/canjs/issues/721 it would be nice to make it possible for the constructor to return something other than the new instance.  This is useful for singleton type setups.

**Comment by justinbmeyer** [comment]
Somehow, we'd need a way to allow setup, or some other function, to return a value other than the instance being created.

```js
Hub.extend({
  setup: function(){
    if(IN INSTANCE STORE){
      // somehow signal to return the instance in the store instead of `this`
    }
  }
})
```

Setup can return an `array` which will be used as the arguments to `init`.  Perhaps it can return some other flag like `new Construct.ReturnValue( somethingElse )` ... which can be used as the return value from the constructor

**Comment by ilyavf** [comment]
This is fixed with https://github.com/canjs/can-construct/pull/30
