### ISSUE TITLE
remove can-construct-proxy from 3.0 can-construct docs

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-construct#36]
@ccummings commented on [Wed Sep 21 2016](https://github.com/canjs/canjs/issues/2510)

can-construct-proxy will not exist in 3.0 so it should be removed from the docs.

**Comment by justinbmeyer** [comment]
probably just need to check that `.proxy` isn't referenced here: http://canjs.com/doc/can-construct.html

**Comment by andrejewski** [comment]
There is no mention of `can-construct-proxy` in the docs or the `can-construct` project.
