### ISSUE TITLE
Parameter CleanUp

### ISSUE THREAD

**Issue by BigAB** [canjs/can-construct#6]
_(Lovingly copy'pasted from https://github.com/canjs/can-define/issues/21)_
I have always considered the arguments passed in to Map.extend params confusing and unintuitive.

`can.DefineMap.extend( instancePropsMethods )` -> one argument extends the prototype
`can.DefineMap.extend( static, instancePropsMethods )` -> if I add a second argument, I have to move the options to the second position because now the first position extends the constructors 'static' methods
`can.DefineMap.extend(  'name', static, instancePropsMethods )` -> to add a name I have to shift it all down because the first argument is now a string for name.

I can't think other examples in other popular libraries that make you shift around your arguments depending on how many you provide.

With this as an opportunity to break from the legacy confusion, would you consider a signature like:

`can.DefineMap.extend(prototype, [,static]  [, options:{ name } ])`
_where options would be an optional argument which is an object with an optional name property_

**Comment by justinbmeyer** [comment]
I'm not sure why there's an `options` argument when all it's ever going to take is the name.

Other thoughts from people can be found here: http://forums.donejs.com/t/an-opportunity-to-clean-up-some-legacy-api-stuff/308

I don't think this is going to be something in 3.0, but lets keep this open to discus for 4.0.  (_my secret hope is that we can use ES Class declarations by then_).

**Comment by BigAB** [comment]
> I'm not sure why there's an `options` argument when all it's ever going to take is the name.

Premature change maybe, I was just thinking if there ever **were** more options added, this way it would be a minor version change rather than a major version change, because we could add to the options object rather than changing the signature.  But totally not a deal breaker, it's an old API and if there has never been anything other than name before, chances are there won't be any new options in the future.

**Comment by rjgotten** [comment]
If anything, wouldn't it be more sane to have a single options object where all parameters are essentially optional?

```js
Construct.extend({
  name      : "..."
  static    : { /* ... */  },
  prototype : { /* ... */  }
});
```

This also allows you to more neatly organize static and prototype members; it clearly labels and indents those sections of a class definition.

**Comment by justinbmeyer** [comment]
@rjgotten I don't think it's worth it as 90% of most types are just prototype definitions.

**Comment by justinbmeyer** [comment]
I'm closing this.   In 4.0, we should hopefully not need can-construct anymore.
